baseurl                  = "https://mica-92.github.io/ninni/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Maria Micaela Ninni"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "cold.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Maria Micaela Ninni"
    nameText             = "Maria Micaela Ninni"
    meText               = "Ph.D. Student"

# Metadata for Open Graph and Twitter
    description          = "A new Hugo site."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Cal me Sam"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "https://themes.gohugo.io//theme/hugo-theme-sam/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/content/2Fs.png"
[params.videoBackground]
    overlay = "rgba(3 , 2, 5, 0.65)" # optional

[[params.mainMenu]]
    link = "trial"
    text = "TRIAL"

[[params.mainMenu]]
    link = "hello"
    text = "hello!"

[[params.mainMenu]]
    link = "cv"
    text = "vitae"

[[params.mainMenu]]
    link = "research"
    text = "research"

[[params.mainMenu]]
    link = "contact"
    text = "contact"

[[params.mainMenu]]
    link = "posts"
    text = "posts"

[imaging]
    quality = 75
